export const QUESTION_CREATE_REQUEST = 'QUESTION_CREATE_REQUEST'
export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS'
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL'
export const QUESTION_CREATE_RESET = 'QUESTION_CREATE_RESET'

export const QUESTION_UPDATE_REQUEST = 'QUESTION_UPDATE_REQUEST'
export const QUESTION_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS'
export const QUESTION_UPDATE_FAIL = 'QUESTION_UPDATE_FAIL'
export const QUESTION_UPDATE_RESET = 'QUESTION_UPDATE_RESET'

export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST'
export const QUESTION_LIST_SUCCESS = 'QUESTION_LISR_SUCCESS'
export const QUESTION_LIST_FAIL = 'QUESTION_LIST_FAIL'

export const QUESTION_REMOVE_REQUEST = 'QUESTION_REMOVE_REQUEST'
export const QUESTION_REMOVE_SUCCESS  = 'QUESTION_REMOVE_SUCCESS'
export const QUESTION_REMOVE_FAIL = 'QUESTION_REMOVE_FAIL'