export const QUIZ_CREATE_REQUEST = 'QUIZ_CREATE_REQUEST'
export const QUIZ_CREATE_SUCCESS = 'QUIZ_CREATE_SUCCESS'
export const QUIZ_CREATE_FAIL = 'QUIZ_CREATE_FAIL'
export const QUIZ_CREATE_RESET = 'QUIZ_CREATE_RESET'

export const QUIZ_UPDATE_REQUEST = 'QUIZ_UPDATE_REQUEST'
export const QUIZ_UPDATE_SUCCESS = 'QUIZ_UPDATE_SUCCESS'
export const QUIZ_UPDATE_FAIL = 'QUIZ_UPDATE_FAIL'
export const QUIZ_UPDATE_RESET = 'QUIZ_UPDATE_RESET'

export const QUIZ_LIST_REQUEST = 'QUIZ_LIST_REQUEST'
export const QUIZ_LIST_SUCCESS = 'QUIZ_LIST_SUCCESS'
export const QUIZ_LIST_FAIL = 'QUIZ_LIST_FAIL'

export const QUIZ_REMOVE_REQUEST = 'QUIZ_REMOVE_REQUEST'
export const QUIZ_REMOVE_SUCCESS = 'QUIZ_REMOVE_SUCCESS'
export const QUIZ_REMOVE_FAIL = 'QUIZ_REMOVE_FAIL'

export const QUIZ_START_REQUEST = 'QUIZ_START_REQUEST'
export const QUIZ_START_SUCCESS = 'QUIZ_START_SUCCESS'
export const QUIZ_START_FAIL = 'QUIZ_START_FAIL'

export const QUIZ_CHECK_REQUEST = 'QUIZ_CHECK_REQUEST'
export const QUIZ_CHECK_SUCCESS = 'QUIZ_CHECK_SUCCESS'
export const QUIZ_CHECK_FAIL = 'QUIZ_CHECK_FAIL'

export const QUIZ_ENROLL_REQUEST = 'QUIZ_ENROLL_REQUEST'
export const QUIZ_ENROLL_SUCCESS = 'QUIZ_ENROLL_SUCCESS'
export const QUIZ_ENROLL_FAIL = 'QUIZ_ENROLL_FAIL'

export const QUIZ_UNENROLL_REQUEST = 'QUIZ_UNENROLL_REQUEST'
export const QUIZ_UNENROLL_SUCCESS = 'QUIZ_UNENROLL_SUCCESS'
export const QUIZ_UNENROLL_FAIL = 'QUIZ_UNENROLL_FAIL'

export const QUIZ_LIST_ENROLLED_REQUEST = 'QUIZ_LIST_ENROLLED_REQUEST'
export const QUIZ_LIST_ENROLLED_SUCCESS = 'QUIZ_LIST_ENROLLED_SUCCESS'
export const QUIZ_LIST_ENROLLED_FAIL = 'QUIZ_LIST_ENROLLED_FAIL'

export const QUIZ_RESET_REQUEST = 'QUIZ_RESET_REQUEST'
export const QUIZ_RESET_SUCCESS = 'QUIZ_RESET_SUCCESS'
export const QUIZ_RESET_FAIL = 'QUIZ_RESET_FAIL'

export const QUIZ_STUDENT_RESPONSE_REQUEST = 'QUIZ_STUDENT_RESPONSE_REQUEST'
export const QUIZ_STUDENT_RESPONSE_SUCCESS = 'QUIZ_STUDENT_RESPONSE_SUCCESS'
export const QUIZ_STUDENT_RESPONSE_FAIL = 'QUIZ_STUDENT_RESPONSE_FAIL'

export const QUIZ_DETAILS_REQUEST = 'QUIZ_DETAILS_REQUEST'
export const QUIZ_DETAILS_SUCCESS = 'QUIZ_DETAILS_SUCCESS'
export const QUIZ_DETAILS_FAIL = 'QUIZ_DETAILS_FAIL'

export const QUIZ_LIST_BY_AUTHOR_REQUEST = 'QUIZ_LIST_BY_AUTHOR_REQUEST'
export const QUIZ_LIST_BY_AUTHOR_SUCCESS = 'QUIZ_LIST_BY_AUTHOR_SUCCESS'
export const QUIZ_LIST_BY_AUTHOR_FAIL = 'QUIZ_LIST_BY_AUTHOR_FAIL'

export const QUIZ_LIST_STUDENT_REQUEST = 'QUIZ_LIST_STUDENT_REQUEST'
export const QUIZ_LIST_STUDENT_SUCCESS = 'QUIZ_LIST_STUDENT_SUCCESS'
export const QUIZ_LIST_STUDENT_FAIL = 'QUIZ_LIST_STUDENT_FAIL'