export const QUIZA_CREATE_REQUEST = 'QUIZA_CREATE_REQUEST';
export const QUIZA_CREATE_SUCCESS = 'QUIZA_CREATE_SUCCESS'
export const QUIZA_CREATE_FAIL = 'QUIZA_CREATE_FAIL'
export const QUIZA_CREATE_RESET = 'QUIZA_CREATE_RESET'

export const QUIZA_UPDATE_REQUEST = 'QUIZA_UPDATE_REQUEST'
export const QUIZA_UPDATE_SUCCESS = 'QUIZA_UPDATE_SUCCESS'
export const QUIZA_UPDATE_FAIL = 'QUIZA_UPDATE_FAIL'
export const QUIZA_UPDATE_RESET = 'QUIZA_UPDATE_RESET'

export const QUIZA_LIST_REQUEST = 'QUIZA_LIST_REQUEST'
export const QUIZA_LIST_SUCCESS = 'QUIZA_LIST_SUCCESS'
export const QUIZA_LIST_FAIL = 'QUIZA_LIST_FAIL'

export const QUIZA_REMOVE_REQUEST = 'QUIZA_REMOVE_REQUEST'
export const QUIZA_REMOVE_SUCCESS = 'QUIZA_REMOVE_SUCCESS'
export const QUIZA_REMOVE_FAIL = 'QUIZA_REMOVE_FAIL'

export const QUIZA_DETAILS_REQUEST = 'QUIZA_DETAILS_REQUEST'
export const QUIZA_DETAILS_SUCCESS = 'QUIZA_DETAILS_SUCCESS'
export const QUIZA_DETAILS_FAIL = 'QUIZA_DETAILS_FAIL'

export const QUIZA_ENROLL_REQUEST = 'QUIZA_ENROLL_REQUEST'
export const QUIZA_ENROLL_SUCCESS = 'QUIZA_ENROLL_SUCCESS'
export const QUIZA_ENROLL_FAIL = 'QUIZA_ENROLL_FAIL'

export const QUIZA_MYENROLLED_LIST_REQUEST = 'QUIZA_MYENROLLED_LIST_REQUEST'
export const QUIZA_MYENROLLED_LIST_SUCCESS = 'QUIZA_MYENROLLED_LIST_SUCCESS'
export const QUIZA_MYENROLLED_LIST_FAIL = 'QUIZA_MYENROLLED_LIST_FAIL'

export const QUIZA_FINES_REQUEST = 'QUIZA_FINES_REQUEST'
export const QUIZA_FINES_SUCCESS = 'QUIZA_FINES_SUCCESS'
export const QUIZA_FINES_FAIL = 'QUIZA_FINES_FAIL'

export const QUIZA_LIST_BY_AUTHOR_REQUEST = 'QUIZA_LIST_BY_AUTHOR_REQUEST'
export const QUIZA_LIST_BY_AUTHOR_SUCCESS = 'QUIZA_LIST_BY_AUTHOR_SUCCESS'
export const QUIZA_LIST_BY_AUTHOR_FAIL = 'QUIZA_LIST_BY_AUTHOR_FAIL'

export const QUIZA_START_REQUEST = 'QUIZA_START_REQUEST'
export const QUIZA_START_SUCCESS = 'QUIZA_START_SUCCESS'
export const QUIZA_START_FAIL = 'QUIZA_START_FAIL'

export const QUIZA_RESET_REQUEST = 'QUIZA_RESET_REQUEST'
export const QUIZA_RESET_SUCCESS = 'QUIZA_RESET_SUCCESS'
export const QUIZA_RESET_FAIL = 'QUIZA_RESET_FAIL'

export const QUIZA_CHECK_REQUEST = 'QUIZA_CHECK_REQUEST'
export const QUIZA_CHECK_SUCCESS = 'QUIZA_CHECK_SUCCESS'
export const QUIZA_CHECK_FAIL = 'QUIZA_CHECK_FAIL'

export const QUIZA_RESPONSES_REQUEST = 'QUIZA_RESPONSES_REQUEST'
export const QUIZA_RESPONSES_SUCCESS = 'QUIZA_RESPONSES_SUCCESS'
export const QUIZA_RESPONSES_FAIL = 'QUIZA_RESPONSES_FAIL'

export const QUIZA_SUBMISSIONS_LIST_REQUEST = 'QUIZA_SUBMISSIONS_LIST_REQUEST'
export const QUIZA_SUBMISSIONS_LIST_SUCCESS = 'QUIZA_SUBMISSIONS_LIST_SUCCESS'
export const QUIZA_SUBMISSIONS_LIST_FAIL = 'QUIZA_SUBMISSIONS_LIST_FAIL'

export const QUIZA_LIST_MY_SUBMISSIONS_REQUEST = 'QUIZA_LIST_MY_SUBMISSIONS_REQUEST'
export const QUIZA_LIST_MY_SUBMISSIONS_SUCCESS = 'QUIZA_LIST_MY_SUBMISSIONS_SUCCESS'
export const QUIZA_LIST_MY_SUBMISSIONS_FAIL = 'QUIZA_LIST_MY_SUBMISSIONS_FAIL'

